apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cloud-app
spec:
  selector:
    app: notification-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
